[PHP]
engine=On
short_open_tag=Off

memory_limit = ${PHP_MEMORY_LIMIT}
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
max_input_time = 300
upload_max_filesize = 100M
post_max_size = 100M

precision=14
output_buffering=4096
serialize_precision=-1
expose_php = Off

error_reporting=E_ALL
display_errors=Off
display_startup_errors=Off

variables_order="EGPCS"
request_order="GP"

[Date]
date.timezone = UTC

[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=0
opcache.save_comments=1
